### ISSUE TITLE
빌드 하지 않을 불필요한 폴더 삭제해주세요 

### ISSUE THREAD

**Issue by iloveuhyeon** [wwwcomcomcomcom/nexus-app#2]
빌드 하지 않을 불필요한 폴더 삭제해주세요 

linux, windows, macos, web 등등

**Comment by wwwcomcomcomcom** [comment]
1a238c368145f36bca96dff20c772cc44acad3df
수정했습니다.
관심 가져주셔서 감사합니다.

**Comment by wwwcomcomcomcom** [comment]
1a238c368145f36bca96dff20c772cc44acad3df
수정했습니다.
관심 가져주셔서 감사합니다.

**Comment by iloveuhyeon** [comment]
LGTM :)
