### ISSUE TITLE
쉼표 찍어주세요 

### ISSUE THREAD

**Issue by iloveuhyeon** [wwwcomcomcomcom/nexus-app#3]
쉼표 찍어주세요 
 
굳이 상관은 없는데 코드 끝에 쉼표 찍으면 vscode에서는 자동 정렬을 해줘요

**Comment by wwwcomcomcomcom** [comment]
d61fe661e9e71aa60f0836bf0743593518b7a2d5
수정했습니다
좋은 의견 감사합니다!

**Comment by iloveuhyeon** [comment]
LGTM :)
